import React, {useState, useEffect} from 'react';
import {HiArrowLongRight} from 'react-icons/hi2';
import settings from '../content/settings.json';
const files=import.meta.glob('../content/projects/*.json',{eager:true,import:'default'});
const projects=Object.values(files).filter(p=>p.published).sort((a,b)=>a.order-b.order);
const cats=['All','Brand Systems','Partnerships','Technical Storytelling','Communications'];
const aliases={'brand-storytelling':'Brand Systems','partnership-campaigns':'Partnerships','technical-storytelling':'Technical Storytelling','communications':'Communications'};
export function safeURL(value){try {const u=new URL(value,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function mediaURL(value){return value?.startsWith('/media/')?value:safeURL(value||'');}
function Arrow(){return <HiArrowLongRight aria-hidden="true" className="arrow"/>;}
function Text({children}){return String(children||'').split('\n\n').map((p,i)=><p key={i}>{p}</p>);}
function Video({block}){const [play,setPlay]=useState(false);const url=safeURL(block.url);let host='';try{host=new URL(url).hostname;}catch{}const trusted=['www.youtube.com','www.youtube-nocookie.com','player.vimeo.com'].includes(host);return <section className="video-block"><h3>{block.title}</h3>{trusted?play?<iframe title={block.title||'Project video'} src={url} allow="fullscreen; picture-in-picture" loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/>:<button className="video-load" onClick={()=>setPlay(true)}>Load video <Arrow/><small>Video loads from {host} when you choose to play.</small></button>:url?<a className="text-link" href={url} target="_blank" rel="noreferrer">View embedded project <Arrow/></a>:null}</section>;}
export function Blocks({blocks=[]}){return blocks.map((b,i)=><div key={i} className={`block space-${b.spacing||'regular'} type-${b.type}`}>
 {b.type==='text'&&<div className={`text-block align-${b.align||'left'}`}><h2>{b.title}</h2><Text>{b.body}</Text></div>}
 {b.type==='image'&&<figure className={b.width==='narrow'?'narrow':''}><img src={mediaURL(b.image)} alt={b.alt||''} loading="lazy"/><figcaption>{b.caption}</figcaption></figure>}
 {b.type==='gallery'&&<><h2>{b.title}</h2><div className={`gallery columns-${b.columns||'2'}`}>{(b.images||[]).map((im,j)=><figure key={j}><img src={mediaURL(im.image)} alt={im.alt||''} loading="lazy"/><figcaption>{im.caption}</figcaption></figure>)}</div></>}
 {b.type==='split'&&<div className={`split image-${b.side||'left'}`}><img src={mediaURL(b.image)} alt={b.alt||''} loading="lazy"/><div><h2>{b.title}</h2><Text>{b.body}</Text></div></div>}
 {b.type==='video'&&<Video block={b}/>}
 </div>);}
function Card({p}){return <article className="project-card"><a href={'/'+p.slug}><div className="cover"><img src={mediaURL(p.cover)} alt={p.coverAlt||p.title} style={{objectPosition:p.coverPosition||'center'}} loading={p.order<2?'eager':'lazy'}/></div><h3>{p.title}</h3><p>{p.company}</p></a></article>;}
function Home({initial='All'}){const [filter,setFilter]=useState(cats.includes(initial)?initial:'All');const list=projects.filter(p=>filter==='All'||p.category===filter);return <><section className="hero"><h1>{settings.headline}</h1><p>{settings.intro}</p><a className="hero-link" href="#work">View selected work <Arrow/></a></section><section id="work" className="work"><h2>Selected work</h2><div className="filters" role="group" aria-label="Filter projects">{cats.map(c=><button key={c} aria-pressed={c===filter} className={c===filter?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className={`project-grid columns-${settings.gridColumns||'2'} gap-${settings.gridGap||'comfortable'}`}>{list.map(p=><Card key={p.slug} p={p}/>)}</div></section></>;}
function Project({p}){const next=projects[(projects.indexOf(p)+1)%projects.length];return <><header className="project-intro"><a className="eyebrow" href={'/?category='+encodeURIComponent(p.category)}>All {p.category.toLowerCase()} <Arrow/></a><h1>{p.title}</h1><p className="summary">{p.summary}</p><dl><div><dt>Company</dt><dd>{p.company}</dd></div><div><dt>Role</dt><dd>{p.role}</dd></div></dl></header><figure className="project-hero"><img src={mediaURL(p.cover)} alt={p.coverAlt}/></figure><section className="overview"><h2>The work</h2><div><Text>{p.overview}</Text></div></section>{p.outcomes?.length>0&&<section className="outcomes" aria-label="Project outcomes">{p.outcomes.map((o,i)=><div key={i}><strong>{o.value}</strong><p>{o.label}</p></div>)}</section>}<Blocks blocks={p.blocks}/><nav className="project-next" aria-label="Next project"><span>Next project</span><a href={'/'+next.slug}>{next.title}<Arrow/></a></nav></>;}
function About(){return <section className="simple-page"><p className="eyebrow">About Ayo</p><h1>The story.<br/>The system.<br/>The people using it.</h1><Text>{settings.about}</Text><a href="/resume" className="text-link">View experience <Arrow/></a></section>;}
function Resume(){return <section className="simple-page"><p className="eyebrow">Experience</p><h1>Brand, web,<br/>and creative direction.</h1>{settings.resume&&<a className="text-link" href={mediaURL(settings.resume)} download>Download résumé <Arrow/></a>}<div className="experience">{[['AppOmni','Senior Visual Designer','Dec 2024–Present'],['Forge HQ','Founder, Creative Director','2020–Present'],['Meta, via TEKSystems','Creative Consultant, Keynote Storytelling (Contract)','2025'],['Secureframe','Principal Designer','2022–2024'],['Navan (TripActions)','Director of Design','2019–2022'],['MongoDB','Creative Director','2015–2019'],['DocuSign','Director of Creative Services','2012–2015']].map(([a,b,c])=><div key={a}><h2>{a}</h2><p>{b}</p><span>{c}</span></div>)}</div></section>;}
function Contact(){return <section className="simple-page"><p className="eyebrow">Contact</p><h1>Have something<br/>in mind?</h1>{settings.email?<a className="contact-link" href={'mailto:'+settings.email}>{settings.email}</a>:settings.contactUrl?<a className="text-link" href={safeURL(settings.contactUrl)}>Get in touch <Arrow/></a>:<p>Contact details will be added before launch.</p>}</section>;}
export function App(){const path=decodeURIComponent(location.pathname).replace(/^\/|\/$/g,'');const [menu,setMenu]=useState(false);const project=projects.find(p=>p.slug===path);const title=project?.title||({about:'About',resume:'Experience',contact:'Contact'}[path])||'Brand systems. Clearer stories.';useEffect(()=>{document.title=title+' | Ayodeji Akintilo';},[title]);return <><a className="skip" href="#main">Skip to content</a><div className="shell"><header className="site-header"><a className="wordmark" href="/">{settings.name}</a><button className="menu-toggle" aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav id="main-nav" className={menu?'open':''} aria-label="Main navigation">{[['Work','/'],['About','/about'],['Resume','/resume'],['Contact','/contact']].map(([name,url])=><a key={url} aria-current={location.pathname===url?'page':undefined} href={url}>{name}</a>)}</nav></header><main id="main">{project?<Project p={project}/>:path==='about'?<About/>:path==='resume'?<Resume/>:path==='contact'?<Contact/>:!path||aliases[path]?<Home initial={aliases[path]||new URLSearchParams(location.search).get('category')||'All'}/>:<section className="simple-page"><h1>Page not found.</h1><a href="/">Explore the work <Arrow/></a></section>}</main><footer><a href="/">{settings.name}</a><a href="/contact">Get in touch <Arrow/></a><a href="/admin/">Edit portfolio</a></footer></div></>;}
