import React, {useState, useEffect, useRef} from 'react';
import {HiArrowLongRight} from 'react-icons/hi2';
import settings from '../content/settings.json';
const files=import.meta.glob('../content/projects/*.json',{eager:true,import:'default'});
const projects=Object.values(files).filter(p=>p.published).sort((a,b)=>a.order-b.order);
const cats=['All','Brand Systems','Partnerships','Technical Storytelling','Communications'];
const aliases={'brand-storytelling':'Brand Systems','partnership-campaigns':'Partnerships','technical-storytelling':'Technical Storytelling','communications':'Communications'};
export function safeURL(value){try {const u=new URL(value,location.origin);return ['http:','https:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function mediaURL(value){if(!value)return '';return value.startsWith('/media/')?value:safeURL(value);}
function Arrow(){return <HiArrowLongRight aria-hidden="true" className="arrow"/>;}
function Text({children}){return String(children||'').split('\n\n').filter(Boolean).map((p,i)=><p key={i}>{p}</p>);}
function Video({block}){const [play,setPlay]=useState(false);const source=block.file||block.url||'';const media=mediaURL(source);const isVideoFile=source.startsWith('/media/')||/\.mp4(?:$|\?)/i.test(source);let host='';try{host=new URL(media).hostname;}catch{}const trusted=['www.youtube.com','www.youtube-nocookie.com','player.vimeo.com'].includes(host);const loop=block.playback!=='controls';return <section className="video-block"><h3>{block.title}</h3>{isVideoFile?<video className="project-video" autoPlay={loop} muted={loop} loop={loop} controls playsInline preload="metadata" poster={block.poster?mediaURL(block.poster):undefined}><source src={media}/></video>:trusted?play?<iframe title={block.title||'Project video'} src={media} allow="fullscreen; picture-in-picture" loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/>:<button className="video-load" onClick={()=>setPlay(true)}>Load video <Arrow/><small>Video loads from {host} when you choose to play.</small></button>:media?<a className="text-link" href={media} target="_blank" rel="noreferrer">View embedded project <Arrow/></a>:null}</section>;}
function BentoGallery({block}){const ref=useRef(null);const layout=block.layout||'bento';useEffect(()=>{const gallery=ref.current;if(!gallery||layout!=='bento')return;let frame;let layoutFrame;let lastWidth=0;const measure=()=>{cancelAnimationFrame(frame);cancelAnimationFrame(layoutFrame);frame=requestAnimationFrame(()=>{const row=parseFloat(getComputedStyle(gallery).gridAutoRows)||8;const gap=parseFloat(getComputedStyle(gallery).rowGap)||0;gallery.querySelectorAll('figure').forEach(figure=>{const image=figure.querySelector('img');if(!image)return;const requested=figure.dataset.size||'auto';let columns={small:4,medium:6,large:8,wide:12}[requested];if(!columns){const ratio=image.naturalWidth&&image.naturalHeight?image.naturalWidth/image.naturalHeight:1.5;columns=ratio>2?12:ratio<1.15?4:6;}figure.style.gridColumnEnd=`span ${columns}`;figure.style.gridRowEnd='auto';});layoutFrame=requestAnimationFrame(()=>gallery.querySelectorAll('figure').forEach(figure=>{const height=figure.getBoundingClientRect().height;figure.style.gridRowEnd=`span ${Math.max(1,Math.ceil((height+gap)/(row+gap)))}`;}));});};const galleryObserver=new ResizeObserver(([entry])=>{const width=entry?.contentRect.width||0;if(Math.abs(width-lastWidth)>.5){lastWidth=width;measure();}});const imageObserver=new ResizeObserver(()=>measure());galleryObserver.observe(gallery);gallery.querySelectorAll('img').forEach(image=>imageObserver.observe(image));measure();return()=>{cancelAnimationFrame(frame);cancelAnimationFrame(layoutFrame);galleryObserver.disconnect();imageObserver.disconnect();};},[layout,block.images]);return <div ref={ref} className={`gallery layout-${layout} columns-${block.columns||'2'}`}>{(block.images||[]).map((im,j)=><figure key={j} data-size={im.size||'auto'}><img src={mediaURL(im.image)} alt={im.alt||''} loading="lazy"/><figcaption>{im.caption}</figcaption></figure>)}</div>;}
function groupGalleries(blocks){return blocks.reduce((result,block)=>{const previous=result[result.length-1];const layout=block.layout||'bento';if(block.type==='gallery'&&layout==='bento'&&previous?.type==='gallery'&&(previous.layout||'bento')==='bento'&&!block.title&&!previous.title){previous.images=[...(previous.images||[]),...(block.images||[])];return result;}result.push({...block,images:block.images?[...block.images]:block.images});return result;},[]);}
export function Blocks({blocks=[]}){return groupGalleries(blocks).map((b,i)=><div key={i} className={`block space-${b.spacing||'regular'} type-${b.type}`}>
 {b.type==='sectionHeading'&&<h2 className="project-section-heading">{b.title}</h2>}
 {b.type==='text'&&<div className={`text-block align-${b.align||'left'}`}>{b.title&&<h2>{b.title}</h2>}<Text>{b.body}</Text></div>}
 {b.type==='image'&&<figure className={b.width==='narrow'?'narrow':''}><img src={mediaURL(b.image)} alt={b.alt||''} loading="lazy"/><figcaption>{b.caption}</figcaption></figure>}
 {b.type==='gallery'&&<>{b.title&&<h2>{b.title}</h2>}<BentoGallery block={b}/></>}
 {b.type==='split'&&<div className={`split image-${b.side||'left'}`}><img src={mediaURL(b.image)} alt={b.alt||''} loading="lazy"/><div><h2>{b.title}</h2><Text>{b.body}</Text></div></div>}
 {b.type==='video'&&<Video block={b}/>}
 </div>);}
function Card({p}){return <article className="project-card"><a href={'/'+p.slug}><div className="cover"><img src={mediaURL(p.cover)} alt={p.coverAlt||p.title} style={{objectPosition:p.coverPosition||'center'}} loading={p.order<2?'eager':'lazy'}/></div><h3>{p.title}</h3><p>{p.company}</p></a></article>;}
function Home({initial='All'}){const [filter,setFilter]=useState(cats.includes(initial)?initial:'All');const list=projects.filter(p=>filter==='All'||p.category===filter);return <><section className="hero"><h1>{settings.headline}</h1><p>{settings.intro}</p><a className="hero-link" href="#work">View selected work <Arrow/></a></section><section id="work" className="work"><h2>Selected work</h2><div className="filters" role="group" aria-label="Filter projects">{cats.map(c=><button key={c} aria-pressed={c===filter} className={c===filter?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className={`project-grid columns-${settings.gridColumns||'2'} gap-${settings.gridGap||'comfortable'}`}>{list.map(p=><Card key={p.slug} p={p}/>)}</div></section></>;}
function Project({p}){const next=projects[(projects.indexOf(p)+1)%projects.length];return <><header className="project-intro"><a className="eyebrow" href={'/?category='+encodeURIComponent(p.category)}>All {p.category.toLowerCase()} <Arrow/></a><h1>{p.title}</h1><p className="summary">{p.summary}</p><dl><div><dt>Company</dt><dd>{p.company}</dd></div><div><dt>Role</dt><dd>{p.role}</dd></div></dl></header><figure className="project-hero"><img src={mediaURL(p.cover)} alt={p.coverAlt}/></figure><section className="overview"><h2>The work</h2><div><Text>{p.overview}</Text></div></section>{p.outcomes?.length>0&&<section className="outcomes" aria-label="Project outcomes">{p.outcomes.map((o,i)=><div key={i}><strong>{o.value}</strong><p>{o.label}</p></div>)}</section>}<Blocks blocks={p.blocks}/><nav className="project-next" aria-label="Next project"><span>Next project</span><a href={'/'+next.slug}>{next.title}<Arrow/></a></nav></>;}
function About(){return <section className="simple-page"><p className="eyebrow">About Ayo</p><h1>The story.<br/>The system.<br/>The people using it.</h1><Text>{settings.about}</Text><a href="/resume" className="text-link">View experience <Arrow/></a></section>;}
function Resume(){return <section className="simple-page"><p className="eyebrow">Experience</p><h1>Brand, web,<br/>and creative direction.</h1>{settings.resume&&<a className="text-link" href={mediaURL(settings.resume)} download>Download résumé <Arrow/></a>}<div className="experience">{[['AppOmni','Senior Visual Designer','Dec 2024–Present'],['Forge HQ','Founder, Creative Director','2020–Present'],['Meta, via TEKSystems','Creative Consultant, Keynote Storytelling (Contract)','2025'],['Secureframe','Principal Designer','2022–2024'],['Navan (TripActions)','Director of Design','2019–2022'],['MongoDB','Creative Director','2015–2019'],['DocuSign','Director of Creative Services','2012–2015']].map(([a,b,c])=><div key={a}><h2>{a}</h2><p>{b}</p><span>{c}</span></div>)}</div></section>;}
function Contact(){return <section className="simple-page"><p className="eyebrow">Contact</p><h1>Have something<br/>in mind?</h1>{settings.email?<a className="contact-link" href={'mailto:'+settings.email}>{settings.email}</a>:settings.contactUrl?<a className="text-link" href={safeURL(settings.contactUrl)}>Get in touch <Arrow/></a>:<p>Contact details will be added before launch.</p>}</section>;}
export function App(){const path=decodeURIComponent(location.pathname).replace(/^\/|\/$/g,'');const [menu,setMenu]=useState(false);const project=projects.find(p=>p.slug===path);const title=project?.title||({about:'About',resume:'Experience',contact:'Contact'}[path])||'Brand systems. Clearer stories.';useEffect(()=>{document.title=title+' | Ayodeji Akintilo';},[title]);return <><a className="skip" href="#main">Skip to content</a><div className="shell"><header className="site-header"><a className="wordmark" href="/">{settings.name}</a><button className="menu-toggle" aria-expanded={menu} aria-controls="main-nav" onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><nav id="main-nav" className={menu?'open':''} aria-label="Main navigation">{[['Work','/'],['About','/about'],['Resume','/resume'],['Contact','/contact']].map(([name,url])=><a key={url} aria-current={location.pathname===url?'page':undefined} href={url}>{name}</a>)}</nav></header><main id="main">{project?<Project p={project}/>:path==='about'?<About/>:path==='resume'?<Resume/>:path==='contact'?<Contact/>:!path||aliases[path]?<Home initial={aliases[path]||new URLSearchParams(location.search).get('category')||'All'}/>:<section className="simple-page"><h1>Page not found.</h1><a href="/">Explore the work <Arrow/></a></section>}</main><footer><a href="/">{settings.name}</a><a href="/contact">Get in touch <Arrow/></a><a href="/admin/">Edit portfolio</a></footer></div></>;}
